dist: bionic

language: java

jdk:
 - openjdk11

cache:
  directories:
   - $HOME/.m2

before_install:
 - git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
 - export PATH=$PATH:$(pwd)/depot_tools
 - wget https://cs.chromium.org/codesearch/f/chromium/src/build/install-build-deps.sh
 - chmod +x install-build-deps.sh
 - sudo ./install-build-deps.sh --no-arm --no-chromeos-fonts --no-nacl --no-prompt
