name: Maven CI

on:
  push:
    branches:
      - master
    paths:
      - "**.cpp"
      - "**.h"
      - "**.java"

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        java: [13]

    env:
      WEBRTC_CACHE_BRANCH: 3987
      WEBRTC_CHECKOUT_FOLDER: ${{ github.workspace }}/.work/webrtc
      WEBRTC_INSTALL_FOLDER: ${{ github.workspace }}/.work/webrtc/build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Linux audio system # Required for testing
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y pulseaudio
          pulseaudio --start

      - name: Set up WebRTC cache
        uses: actions/cache@v1
        with:
          path: ${{ env.WEBRTC_INSTALL_FOLDER }}
          key: webrtc-${{ env.WEBRTC_CACHE_BRANCH }}-${{ runner.os }}-${{ hashFiles('webrtc-jni/pom.xml') }}
          restore-keys: webrtc-${{ env.WEBRTC_CACHE_BRANCH }}-${{ runner.os }}-

      - name: Set up Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build
        run: mvn package -DskipTests -s .github/workflows/settings.xml

      - name: Test
        run: mvn -B jar:jar surefire:test

      - name: Deploy
        env:
          NEXUS_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: mvn deploy -DskipTests -s .github/workflows/settings.xml
