name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up depot tools
      run: |
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "::add-path::$(pwd)/depot_tools"
    - name: Install build dependencies
      run: |
        wget https://cs.chromium.org/codesearch/f/chromium/src/build/install-build-deps.sh
        chmod +x install-build-deps.sh
        sudo ./install-build-deps.sh --no-arm --no-chromeos-fonts --no-nacl --no-prompt
    - name: Build with Maven
      run: mvn -B package -DskipTests -Dmaven.test.skip=true --file pom.xml
